// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/he-he-heng/toktok-backend/ent/attempt"
	"github.com/he-he-heng/toktok-backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attemptFields := schema.Attempt{}.Fields()
	_ = attemptFields
	// attemptDescCnt is the schema descriptor for cnt field.
	attemptDescCnt := attemptFields[0].Descriptor()
	// attempt.DefaultCnt holds the default value on creation for the cnt field.
	attempt.DefaultCnt = attemptDescCnt.Default.(int)
	// attemptDescBreak is the schema descriptor for break field.
	attemptDescBreak := attemptFields[1].Descriptor()
	// attempt.DefaultBreak holds the default value on creation for the break field.
	attempt.DefaultBreak = attemptDescBreak.Default.(bool)
	// attemptDescTimestamp is the schema descriptor for timestamp field.
	attemptDescTimestamp := attemptFields[2].Descriptor()
	// attempt.DefaultTimestamp holds the default value on creation for the timestamp field.
	attempt.DefaultTimestamp = attemptDescTimestamp.Default.(func() time.Time)
}
